name: Build and Deploy gh-pages
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          RACT_APP_APP_ID: ${{ secrets.RACT_APP_APP_ID }}
        run: |
          npm install && npm run-script build
          echo "::warning:: var = ${{ secrets }}"

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: test_deploy
          folder: build
